// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using PureDelivery.Achievments.Infrastucture.Data;

#nullable disable

namespace PureDelivery.Achievments.Infrastucture.Migrations
{
    [DbContext(typeof(AchievmentsDbContext))]
    [Migration("20260415211809_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("PureDelivery.Achievments.Application.Entities.AchievmentDefinition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CalculationType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<string>("EventCriteria")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<double>("LoyaltyPointsReward")
                        .HasColumnType("float");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<double>("TargetValue")
                        .HasColumnType("float");

                    b.HasKey("Id");

                    b.HasIndex("EventCriteria");

                    b.ToTable("AchievementDefinitions", (string)null);
                });

            modelBuilder.Entity("PureDelivery.Achievments.Application.Entities.AchievmentUserProgress", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AchievmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<double>("CurrentValue")
                        .HasColumnType("float");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AchievmentId");

                    b.HasIndex("UserId", "AchievmentId")
                        .IsUnique();

                    b.ToTable("AchievementUserProgress", (string)null);
                });

            modelBuilder.Entity("PureDelivery.Achievments.Application.Entities.UserAchievements", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<Guid>("AchievmentId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uniqueidentifier");

                    b.HasKey("Id");

                    b.HasIndex("AchievmentId");

                    b.HasIndex("UserId");

                    b.ToTable("UserAchievements", (string)null);
                });

            modelBuilder.Entity("PureDelivery.Achievments.Application.Entities.AchievmentUserProgress", b =>
                {
                    b.HasOne("PureDelivery.Achievments.Application.Entities.AchievmentDefinition", "Achievment")
                        .WithMany()
                        .HasForeignKey("AchievmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Achievment");
                });

            modelBuilder.Entity("PureDelivery.Achievments.Application.Entities.UserAchievements", b =>
                {
                    b.HasOne("PureDelivery.Achievments.Application.Entities.AchievmentDefinition", "Achievment")
                        .WithMany()
                        .HasForeignKey("AchievmentId")
                        .OnDelete(DeleteBehavior.NoAction)
                        .IsRequired();

                    b.Navigation("Achievment");
                });
#pragma warning restore 612, 618
        }
    }
}
